### ISSUE TITLE
loading the update

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#118]
Notes
======
loading the update

Environment
======
version: 2.0.1
build: 45
UDID: b7a85baeeacd9bdc
Android Release: 4.4.4
Androind SDK: 19
Brand: google
Device: flo
Stack trace
======
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: android.database.sqlite.SQLiteException: no such column: s.source (code 1): , while compiling: SELECT s.story, s.story_title, s.story_ref, l.language_code FROM stories AS s LEFT JOIN languages AS l ON l.id=s.language_id WHERE s.source=0
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
	at com.door43.translationstudio.migration.SQLiteMigrationHelper.migrateDatabase(SQLiteMigrationHelper.java:138)
	at com.door43.translationstudio.migration.UpdateManager.run(UpdateManager.java:53)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask$1.onSuccess(SplashScreenActivity.java:100)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:70)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:72)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:65)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by neutrinog** [comment]
These exceptions seem to have occur on devices where 1.x was installed but either corrupt or older versions. e.g. missing columns etc. Error handling has been added to catch these exceptions going forward.
