### ISSUE TITLE
I was typing some text and th...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#122]
Notes
======
I was typing some text and then rotated the screen.

Environment
======
version: 2.0.1
build: 45
UDID: 14f7475dec5fae5d
Android Release: 4.2.2
Androind SDK: 17
Brand: Xiaomi
Device: lcsh92_wet_jb9
Stack trace
======
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:205)
	at android.os.Handler.<init>(Handler.java:119)
	at android.widget.Editor$UserDictionaryListener.<init>(Editor.java:3940)
	at android.widget.Editor.<init>(Editor.java:213)
	at android.widget.TextView.createEditorIfNeeded(TextView.java:8684)
	at android.widget.TextView.setText(TextView.java:3665)
	at android.widget.TextView.setText(TextView.java:3607)
	at android.widget.TextView.append(TextView.java:3330)
	at android.widget.TextView.append(TextView.java:3320)
	at com.door43.translationstudio.MainActivity$13$2.run(MainActivity.java:866)
	at com.door43.translationstudio.util.ThreadableUI$1.run(ThreadableUI.java:19)

**Comment by neutrinog** [comment]
added Looper.prepare() to the threadable ui class
