### ISSUE TITLE
tried to launch app

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#133]
Notes
======
tried to launch app

Environment
======
version: 2.0.2
build: 46
UDID: 6984846b09592e9f
Android Release: 4.2.2
Androind SDK: 17
Brand: google
Device: toro
Stack trace
======
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:197)
	at android.os.Handler.<init>(Handler.java:111)
	at android.widget.Editor$UserDictionaryListener.<init>(Editor.java:3836)
	at android.widget.Editor.<init>(Editor.java:192)
	at android.widget.TextView.createEditorIfNeeded(TextView.java:8475)
	at android.widget.TextView.setText(TextView.java:3611)
	at android.widget.TextView.setText(TextView.java:3554)
	at android.widget.TextView.append(TextView.java:3277)
	at android.widget.TextView.append(TextView.java:3267)
	at com.door43.translationstudio.MainActivity$13$3.run(MainActivity.java:930)
	at com.door43.translationstudio.util.ThreadableUI$1.run(ThreadableUI.java:27)

**Comment by neutrinog** [comment]
see also https://github.com/Door43/translationStudio2/issues/132 This has been fixed.
