### ISSUE TITLE
tried to update from server w...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#138]
Notes
======
tried to update from server when project list was empty, see #137

Environment
======
version: 2.0.2
build: 46
UDID: 9f023fc4659b778f
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: degaswifiue
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.ProjectManager.downloadNewProjects(ProjectManager.java:84)
	at com.door43.translationstudio.MainActivity$18.run(MainActivity.java:1408)

**Comment by neutrinog** [comment]
duplicate https://github.com/Door43/translationStudio2/issues/141
