### ISSUE TITLE
Hit cancel on error report.  ...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#155]
Notes
======
Hit cancel on error report.  Original error was from clicking on a project that seemed to have not been loaded correctly

Environment
======
version: 2.0.2
build: 49
UDID: f668cbd24ac3903
Android Release: 4.4.2
Androind SDK: 19
Brand: Lenovo
Device: YT2
Stack trace
======
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:169)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.loadSelectedProject(SplashScreenActivity.java:148)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.access$500(SplashScreenActivity.java:65)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask$1.onSuccess(SplashScreenActivity.java:120)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:88)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:72)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:65)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by neutrinog** [comment]
This was caused by downloading updates from the server. The current development version of the app does not support the v1 api.
