### ISSUE TITLE
rotated the device while havi...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#184]
Notes
======
rotated the device while having a dialog open in the p2p sharing activity

Environment
======
version: 2.0.3
build: 52
UDID: d00e21b595ca411f
Android Release: 4.1.1
Androind SDK: 16
Brand: generic
Device: vbox86tp
Stack trace
======
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.device2device.DeviceToDeviceActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3512)
	at android.app.ActivityThread.access$700(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:469)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:848)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1802)
	at android.app.Activity.performCreate(Activity.java:5011)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
	... 12 more

**Comment by neutrinog** [comment]
related to https://github.com/Door43/translationStudio2/issues/183

There is some crazy stuff with fragments, and activity lifecycle that is preventing a true fix to this. In the meantime rotation has been disabled on the p2p sharing activity.
