### ISSUE TITLE
Scrolling after inserting ver...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#204]
Notes
======
Scrolling after inserting verse marker

Environment
======
version: 2.0.3
build: 53
UDID: c16d19f40cbe170e
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Stack trace
======
java.lang.StringIndexOutOfBoundsException: length=193; regionStart=92; regionLength=-76
	at java.lang.String.startEndAndLength(String.java:588)
	at java.lang.String.substring(String.java:1475)
	at com.door43.translationstudio.MainActivity.save(MainActivity.java:1214)
	at com.door43.translationstudio.MainActivity$13$1.run(MainActivity.java:652)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Log history
======
1/28/15 1:33 PM [com.door43.translationstudio.network.Connection]:failed to read the message from the socket
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:141)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
	at java.io.InputStreamReader.read(InputStreamReader.java:233)
	at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
	at java.io.BufferedReader.readLine(BufferedReader.java:397)
	at com.door43.translationstudio.network.Connection.readLine(Connection.java:58)
	at com.door43.translationstudio.network.Client$ServerThread.run(Client.java:187)
	at java.lang.Thread.run(Thread.java:841)

**Comment by neutrinog** [comment]
this is occurring during the save when spanned strings are being compiled down into raw text (e.g. usx).
