### ISSUE TITLE
Followed updated prompt

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#222]
Notes
======
Followed updated prompt

Environment
======
version: 2.0.3
build: 51
UDID: e7848e883731e8e0
Android Release: 4.1.2
Androind SDK: 16
Brand: verizon
Device: ADR930L
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:723)
	at com.door43.translationstudio.projects.ProjectManager.downloadNewProjects(ProjectManager.java:97)
	at com.door43.translationstudio.MainActivity$21.run(MainActivity.java:1538)
Log history
======
1/30/15 5:45 PM [com.door43.translationstudio.projects.data.DataStore]:clearing the asset cache to support api version 2

**Comment by neutrinog** [comment]
fixed in the latest releases
