### ISSUE TITLE
app was backgrounded for a fe...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#225]
Notes
======
app was backgrounded for a few hours

Environment
======
version: 2.0.3
build: 51
UDID: dd19773da22f5f
Android Release: 4.4.4
Androind SDK: 19
Brand: Verizon
Device: kltevzw
Stack trace
======
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.ProjectSettingsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2497)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5678)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.door43.translationstudio.ProjectSettingsActivity.loadValues(ProjectSettingsActivity.java:66)
	at com.door43.translationstudio.ProjectSettingsActivity.onCreate(ProjectSettingsActivity.java:57)
	at android.app.Activity.performCreate(Activity.java:5586)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	... 11 more

**Comment by neutrinog** [comment]
dup https://github.com/Door43/translationStudio2/issues/224
