### ISSUE TITLE
Clicking on luke

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#228]
Notes
======
Clicking on luke

Environment
======
version: 2.0.3
build: 54
UDID: e7848e883731e8e0
Android Release: 4.1.2
Androind SDK: 16
Brand: verizon
Device: ADR930L
Stack trace
======
java.lang.RuntimeException: Could not dispatch event: class com.door43.translationstudio.events.ChoseProjectEvent to handler [EventHandler public void com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.onSelectedProjectFromMeta(com.door43.translationstudio.events.ChoseProjectEvent)]: null
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
	at com.squareup.otto.Bus.dispatch(Bus.java:386)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
	at com.squareup.otto.Bus.post(Bus.java:336)
	at com.door43.translationstudio.util.MainThreadBus.post(MainThreadBus.java:35)
	at com.door43.translationstudio.dialogs.ChooseProjectDialog$1.onItemClick(ChooseProjectDialog.java:59)
	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2859)
	at android.widget.AbsListView$1.run(AbsListView.java:3533)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4856)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.door43.translationstudio.panes.left.tabs.FramesTabFragment.onCreateView(FramesTabFragment.java:34)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
	at android.app.BackStackRecord.run(BackStackRecord.java:635)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:437)
	at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:555)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
	at com.door43.translationstudio.panes.left.LeftPaneSlidingTabsFragment.selectTab(LeftPaneSlidingTabsFragment.java:74)
	at com.door43.translationstudio.panes.left.LeftPaneFragment.selectTab(LeftPaneFragment.java:34)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.handleProjectSelection(ProjectsTabFragment.java:95)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.onSelectedProjectFromMeta(ProjectsTabFragment.java:144)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
	at com.squareup.otto.Bus.dispatch(Bus.java:384)
	... 17 more

**Comment by neutrinog** [comment]
I think this was related to getActivity returning null.
