### ISSUE TITLE
importing Ruth a second time ...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#252]
Notes
======
importing Ruth a second time in a clean install

Environment
======
version: 2.0.3
build: 55
UDID: e59d02e45e77051f
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.imports.ProjectImport.getTitle(ProjectImport.java:45)
	at com.door43.translationstudio.dialogs.ProjectImportAprovalAdapter.getGroupView(ProjectImportAprovalAdapter.java:99)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
	at android.widget.AbsListView.obtainView(AbsListView.java:2263)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
	at android.widget.ListView.onMeasure(ListView.java:1175)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16504)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2552)
	at android.view.View.measure(View.java:16504)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5081)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)
Log history
======
2/5/15 5:38 PM [com.door43.translationstudio.projects.Project]:Missing project source
t cache to support api version 2.2

**Comment by neutrinog** [comment]
The target (device to which the project was to be downloaded) did not have the source for the project ruth yet.

**Comment by neutrinog** [comment]
because the source does not exist on the device gets a null pointer exception while looking up the project title while generating the import approval dialog.

**Comment by neutrinog** [comment]
we will likely want to automatically download the source from the peer if it is missing.
The ProjectImport has been updated to identify when the source is missing so we just need to implement that in the p2p sharing activity.

**Comment by neutrinog** [comment]
project sources will now be imported when necessary during the p2p sharing process
