### ISSUE TITLE
obs did not load in far left ...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#272]
Notes
======
obs did not load in far left field. I had to close and reopen app

Environment
======
version: 2.0.3
build: 51
UDID: 6d143e8d5fadb846
Android Release: 4.4.4
Androind SDK: 19
Brand: motorola
Device: peregrine
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:723)
	at com.door43.translationstudio.projects.ProjectManager.downloadNewProjects(ProjectManager.java:97)
	at com.door43.translationstudio.MainActivity$21.run(MainActivity.java:1538)
Log history
======
1/23/15 2:16 PM [com.door43.translationstudio.projects.data.DataStore]:clearing the asset cache to support api version 2

**Comment by neutrinog** [comment]
I think I already fixed this just after releasing this build but I will double check.

**Comment by neutrinog** [comment]
just noticed this is build 51, which is definitely super old and buggy.
