### ISSUE TITLE
Opening the settings menu

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#287]
Notes
======
Opening the settings menu

Environment
======
version: 2.1.0
build: 56
UDID: f668cbd24ac3903
Android Release: 4.4.2
Androind SDK: 19
Brand: Lenovo
Device: YT2
Stack trace
======
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.SettingsActivity}: java.lang.IllegalArgumentException: No view found for id 0x1020305 (android:id/prefs) for fragment GeneralPreferenceFragment{229e86c8 #0 id=0x1020305}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2329)
	at android.app.ActivityThread.access$800(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x1020305 (android:id/prefs) for fragment GeneralPreferenceFragment{229e86c8 #0 id=0x1020305}
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:882)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.Activity.performStart(Activity.java:5279)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2252)
	... 11 more

**Comment by neutrinog** [comment]
duplicated https://github.com/Door43/translationStudio2/issues/303
