### ISSUE TITLE
tapping settings

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#304]
Notes
======
tapping settings

Environment
======
version: 2.1.0
build: 56
UDID: d53a67a41c214aba
Android Release: 4.4.2
Androind SDK: 19
Brand: Allwinner-Tablet
Device: fiber-wifibt_mtk
Stack trace
======
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.SettingsActivity}: java.lang.IllegalArgumentException: No view found for id 0x10202f6 (android:id/prefs) for fragment GeneralPreferenceFragment{422b2d98 #0 id=0x10202f6}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x10202f6 (android:id/prefs) for fragment GeneralPreferenceFragment{422b2d98 #0 id=0x10202f6}
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:882)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.Activity.performStart(Activity.java:5240)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
	... 11 more

**Comment by neutrinog** [comment]
duplicate https://github.com/Door43/translationStudio2/issues/303
