### ISSUE TITLE
Legacy progress dialog is causing app to crash

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#309]
Notes
======
p

Environment
======
version: 2.0.3
build: 51
UDID: 22fd637299362c77
Android Release: 4.4.2
Androind SDK: 19
Brand: iRULU
Device: t10
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.MainApplication.showProgressDialog(MainApplication.java:368)
	at com.door43.translationstudio.MainApplication.showProgressDialog(MainApplication.java:390)
	at com.door43.translationstudio.SharingActivity$2$2$1.run(SharingActivity.java:149)

**Comment by neutrinog** [comment]
we just need to remove the legacy progress bar method.
