### ISSUE TITLE
selecting luke

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#317]
Notes
======
selecting luke

Environment
======
version: 2.1.1
build: 57
UDID: 345d81bb2e44e64a
Android Release: 5.0.2
Androind SDK: 21
Brand: google
Device: grouper
Stack trace
======
java.lang.RuntimeException: Could not dispatch event: class com.door43.translationstudio.events.ChoseProjectEvent to handler [EventHandler public void com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.onSelectedProjectFromMeta(com.door43.translationstudio.events.ChoseProjectEvent)]: Attempt to invoke virtual method 'com.door43.translationstudio.projects.Frame com.door43.translationstudio.projects.Chapter.getSelectedFrame()' on a null object reference
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
	at com.squareup.otto.Bus.dispatch(Bus.java:386)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
	at com.squareup.otto.Bus.post(Bus.java:336)
	at com.door43.translationstudio.util.MainThreadBus.post(MainThreadBus.java:35)
	at com.door43.translationstudio.dialogs.ChooseProjectDialog$1.onItemClick(ChooseProjectDialog.java:61)
	at android.widget.AdapterView.performItemClick(AdapterView.java:300)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3845)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3617)
	at android.view.View.dispatchTouchEvent(View.java:8388)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:765)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
	at android.view.View.dispatchPointerEvent(View.java:8578)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5675)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5646)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5791)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.door43.translationstudio.projects.Frame com.door43.translationstudio.projects.Chapter.getSelectedFrame()' on a null object reference
	at com.door43.translationstudio.MainActivity.reloadCenterPane(MainActivity.java:1039)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.handleProjectSelection(ProjectsTabFragment.java:91)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment.onSelectedProjectFromMeta(ProjectsTabFragment.java:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
	at com.squareup.otto.Bus.dispatch(Bus.java:384)
	... 53 more
Log history
======
2/17/15 12:16 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/17/15 12:16 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:13
2/17/15 12:16 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:21:37
2/17/15 12:06 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/17/15 12:06 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:13
2/17/15 12:06 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:21:37
2/17/15 12:01 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/17/15 12:01 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:13
2/17/15 12:01 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:21:37
2/17/15 12:00 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.3
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project gen
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rev
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project phm
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jud
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jas
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project act
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 2ti
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 1ti
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/13/15 7:43 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project gen
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rev
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project phm
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jud
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jas
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project act
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 2ti
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 1ti
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/13/15 7:42 AM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/12/15 1:32 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/12/15 1:32 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rev
2/12/15 1:32 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project phm
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jud
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jas
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project act
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 2ti
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 1ti
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/12/15 1:31 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rev
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project phm
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jud
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jas
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project act
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 2ti
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 1ti
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/11/15 3:41 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/11/15 7:55 AM [com.door43.translationstudio.projects.ProjectManager]:The notes were not found for project 2ti
eTranslations/2ti/en/udb/notes.json

**Comment by neutrinog** [comment]
I think this was related to getActivity returning null.
