### ISSUE TITLE
App rebooted probably due to ...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#333]
Notes
======
App rebooted probably due to memory then crashed when starting up again.

Environment
======
version: 2.1.2
build: 61
UDID: f668cbd24ac3903
Android Release: 4.4.2
Androind SDK: 19
Brand: Lenovo
Device: YT2
Stack trace
======
java.lang.RuntimeException: Unable to resume activity {com.translationstudio.androidapp/com.door43.translationstudio.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2872)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2975)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5283)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.door43.translationstudio.panes.left.tabs.ChaptersTabFragment.NotifyAdapterDataSetChanged(ChaptersTabFragment.java:66)
	at com.door43.translationstudio.panes.left.LeftPaneFragment.reloadChaptersTab(LeftPaneFragment.java:112)
	at com.door43.translationstudio.MainActivity.onResume(MainActivity.java:261)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
	at android.app.Activity.performResume(Activity.java:5349)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2862)
	... 10 more
Log history
======
2/20/15 12:30 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note rut:04:18
2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/en/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/pt-br/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/pt-br/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link target_languages.link
java.io.FileNotFoundException: target_languages.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTargetLanguageCatalog(DataStore.java:471)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:99)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:implicitexplicit
2/20/15 12:30 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note rut:04:18
2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/en/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/pt-br/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/pt-br/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link target_languages.link
java.io.FileNotFoundException: target_languages.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTargetLanguageCatalog(DataStore.java:471)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:99)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/20/15 12:30 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.5

**Comment by neutrinog** [comment]
first,  we probably do not need to log an error when the link is not found.

**Comment by neutrinog** [comment]
This was a combination of memory leaks and bugs in the threads
