### ISSUE TITLE
I only have Arabic as my sour...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#338]
Notes
======
I only have Arabic as my source language in NT

Environment
======
version: 2.1.2
build: 61
UDID: e7848e883731e8e0
Android Release: 4.1.2
Androind SDK: 16
Brand: verizon
Device: ADR930L
Log history
======
2/21/15 11:52 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to load the packaged asset sourceTranslations/jhn/ar/avd/notes.json
java.io.FileNotFoundException: sourceTranslations/jhn/ar/avd/notes.json
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:715)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchNotes(DataStore.java:537)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:181)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:52 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to load the linked packaged asset sourceTranslations/jhn/ar/avd/notes.json
java.io.FileNotFoundException: data/06ad6b73a2d560cec383c276233d5b28
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:706)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchNotes(DataStore.java:537)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:181)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:52 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to load the packaged asset sourceTranslations/jhn/ar/avd/terms.json
java.io.FileNotFoundException: sourceTranslations/jhn/ar/avd/terms.json
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:715)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTerms(DataStore.java:489)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:173)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:52 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to load the linked packaged asset sourceTranslations/jhn/ar/avd/terms.json
java.io.FileNotFoundException: data/c715f14251430b88a803b0094d5c18b9
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:706)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTerms(DataStore.java:489)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:173)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:51 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/21/15 11:51 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/en/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:51 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/pt-br/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/pt-br/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:51 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link target_languages.link
java.io.FileNotFoundException: target_languages.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:315)
	at android.content.res.AssetManager.open(AssetManager.java:289)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTargetLanguageCatalog(DataStore.java:471)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:99)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

2/21/15 11:51 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.5
2/16/15 12:18 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/16/15 12:18 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:20:17
2/16/15 12:18 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:10:16
2/16/15 12:18 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:06:31
2/16/15 12:18 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:01:54
2/16/15 12:18 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term servant
2/16/15 9:10 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/16/15 9:10 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:20:17
2/16/15 9:10 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:10:16
2/16/15 9:10 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:06:31
2/16/15 9:10 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:01:54
2/16/15 8:17 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/16/15 8:17 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:20:17
2/16/15 8:17 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:10:16
2/16/15 8:17 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:06:31
2/16/15 8:17 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:01:54

**Comment by neutrinog** [comment]
I suspect it is only the abundance of Arabic text that is causing concern, but this is not a bug.
