### ISSUE TITLE
It would be helpful if the ba...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#340]
Notes
======
It would be helpful if the back key performed the same as it does in most other Android devices - closing the open page and returning to the previous page, rather than closing the app. I have stumbled over this repeatedly while exploring the app.

Environment
======
version: 2.1.2
build: 61
UDID: d78133fd1df2b28e
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: jflterefreshspr
Log history
======
2/23/15 10:16 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
2/23/15 10:12 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/en/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/23/15 10:12 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/pt-br/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/pt-br/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/23/15 10:12 AM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link target_languages.link
java.io.FileNotFoundException: target_languages.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTargetLanguageCatalog(DataStore.java:471)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:99)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/23/15 10:12 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.5

**Comment by neutrinog** [comment]
This app is currently functioning according to standard navigation guidelines.
