### ISSUE TITLE
downloading updates

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#372]
Notes
======
downloading updates

Environment
======
version: 2.1.2
build: 61
UDID: cd492e4a3fc8d847
Android Release: 4.1.1
Androind SDK: 16
Brand: samsung
Device: d2att
Stack trace
======
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:672)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:368)
	at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:160)
	at android.app.Dialog.dismissDialog(Dialog.java:319)
	at android.app.Dialog.dismiss(Dialog.java:302)
	at com.door43.translationstudio.CrashReporterActivity$UploadReportsTask$3.run(CrashReporterActivity.java:191)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4918)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by neutrinog** [comment]
2.1.3
