### ISSUE TITLE
rotating after enabling blind...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#439]
Notes
======
rotating after enabling blind draft mode

Environment
======
version: 2.1.5
build: 80
UDID: c16d19f40cbe170e
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.translator.BlindDraftTranslatorFragment.onCreateOptionsMenu(BlindDraftTranslatorFragment.java:887)
	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:1780)
	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1927)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2539)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
	at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
	at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
	at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
	at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
	at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:543)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5081)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)
Log history
======
4/16/15 5:30 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term God the Son
4/16/15 5:01 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9

**Comment by neutrinog** [comment]
this issues occurs not matter what fragment is loaded in the translator.
