### ISSUE TITLE
clicked export to SD card

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#455]
Notes
======
clicked export to SD card

Environment
======
version: 2.1.5
build: 80
UDID: 3859d5fba1b1d91d
Android Release: 4.4.4
Androind SDK: 19
Brand: Verizon
Device: kltevzw
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.Sharing.exportDW(Sharing.java:1039)
	at com.door43.translationstudio.SharingActivity$4$1.run(SharingActivity.java:220)
	at com.door43.util.threads.ThreadableUI$1.run(ThreadableUI.java:27)
Log history
======
4/28/15 4:58 PM  E/com.door43.translationstudio.projects.Project: failed to fetch the git commit
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:821)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:845)
	at com.door43.translationstudio.projects.Sharing.exportDW(Sharing.java:1039)
	at com.door43.translationstudio.SharingActivity$4$1.run(SharingActivity.java:220)
	at com.door43.util.threads.ThreadableUI$1.run(ThreadableUI.java:27)

4/12/15 12:34 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9
3/24/15 6:54 AM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.7
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:obs:notes:frames:01-11
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:obs:notes:frames:01-11
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:obs:notes:frames:01-11
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:obs:notes:frames:01-11
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:obs:notes:frames:01-11
2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/obs/notes.link
java.io.FileNotFoundException: sourceTranslations/obs/en/obs/notes.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchNotes(DataStore.java:537)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:181)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/obs/terms.link
java.io.FileNotFoundException: sourceTranslations/obs/en/obs/terms.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTerms(DataStore.java:489)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:173)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/obs/source.link
java.io.FileNotFoundException: sourceTranslations/obs/en/obs/source.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchSource(DataStore.java:585)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:164)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:149)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:131)
	at com.door43.translationstudio.panes.left.tabs.ProjectsTabFragment$LoadProjectTask.doInBackground(ProjectsTabFragment.java:127)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:implicitexplicit
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:implicitexplicit
2/26/15 4:07 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vocabulary:implicitexplicit
2/26/15 4:07 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note tit:03:15
2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/en/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/en/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link sourceTranslations/obs/pt-br/resources_catalog.link
java.io.FileNotFoundException: sourceTranslations/obs/pt-br/resources_catalog.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchResourceCatalog(DataStore.java:441)
	at com.door43.translationstudio.projects.ProjectManager.loadSourceLanguageCatalog(ProjectManager.java:847)
	at com.door43.translationstudio.projects.ProjectManager.loadProjectsCatalog(ProjectManager.java:740)
	at com.door43.translationstudio.projects.ProjectManager.initProjects(ProjectManager.java:114)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:102)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  E/com.door43.translationstudio.projects.data.DataStore: failed to read the key from the asset link target_languages.link
java.io.FileNotFoundException: target_languages.link
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.door43.translationstudio.projects.data.DataStore.resolvePackagedLink(DataStore.java:247)
	at com.door43.translationstudio.projects.data.DataStore.loadPackagedJSONAsset(DataStore.java:702)
	at com.door43.translationstudio.projects.data.DataStore.loadJSONAsset(DataStore.java:690)
	at com.door43.translationstudio.projects.data.DataStore.fetchTargetLanguageCatalog(DataStore.java:471)
	at com.door43.translationstudio.projects.ProjectManager.init(ProjectManager.java:99)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:108)
	at com.door43.translationstudio.SplashScreenActivity$LoadAppTask.doInBackground(SplashScreenActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

2/26/15 4:07 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.5
2/11/15 2:20 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.2

**Comment by neutrinog** [comment]
same as https://github.com/Door43/translationStudio2/issues/481
