### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#481]
Notes
======
idk

Environment
======
version: 2.1.5
build: 80
UDID: f6db20a020d1152c
Android Release: 4.4.3
Androind SDK: 19
Brand: google
Device: hammerhead
Stack trace
======
java.lang.NullPointerException
	at com.door43.translationstudio.projects.Sharing.exportDW(Sharing.java:1039)
	at com.door43.translationstudio.SharingActivity$3$1.run(SharingActivity.java:147)
	at com.door43.util.threads.ThreadableUI$1.run(ThreadableUI.java:27)
Log history
======
5/19/15 6:41 PM  E/com.door43.translationstudio.projects.Project: failed to fetch the git commit
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:821)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:845)
	at com.door43.translationstudio.projects.Sharing.exportDW(Sharing.java:1039)
	at com.door43.translationstudio.SharingActivity$3$1.run(SharingActivity.java:147)
	at com.door43.util.threads.ThreadableUI$1.run(ThreadableUI.java:27)

5/19/15 6:36 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term isaac
5/19/15 6:36 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term sarah
5/19/15 3:25 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9

**Comment by neutrinog** [comment]
this is line `1060` in build 82
